import{a as b,S as w,i}from"./assets/vendor-Dr9nwXt6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",q="54645624-93bc72701cdff138f1edf2876",u=15;async function v(r,t=1){const s=r.trim(),{data:n}=await b.get(S,{params:{key:q,q:s,page:t,per_page:u,image_type:"photo",orientation:"horizontal",safesearch:!0}});return n}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),M=new w(".gallery a",{captionsData:"alt",captionDelay:250});function P(r){const t=r.map(({webformatURL:s,largeImageURL:n,tags:e,likes:o,views:a,comments:h,downloads:L})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${s}" alt="${e}" loading="lazy"/>
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b><span>${o}</span></p>
            <p class="info-item"><b>Views</b><span>${a}</span></p>
            <p class="info-item"><b>Comments</b><span>${h}</span></p>
            <p class="info-item"><b>Downloads</b><span>${L}</span></p>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",t),M.refresh()}function E(){f.innerHTML=""}function B(){m.classList.remove("is-hidden")}function R(){m.classList.add("is-hidden")}function $(){p.classList.remove("is-hidden")}function l(){p.classList.add("is-hidden")}const y=document.querySelector(".form"),A=document.querySelector(".load-more");let d="",c=1;y.addEventListener("submit",O);A.addEventListener("click",x);async function O(r){r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(!t){i.error({message:"Please enter a search query!",position:"topRight"});return}t!==d&&(d=t,c=1,E()),l(),await g({isLoadMore:!1}),y.reset()}async function x(){await g({isLoadMore:!0})}async function g({isLoadMore:r}){try{B();const t=await v(d,c),{hits:s,totalHits:n}=t;if(!s.length){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l();return}P(s),c+=1;const e=Math.ceil(n/u);c>e?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):$(),r&&_()}catch{i.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{R()}}function _(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
